# This is a basic workflow that is manually triggered

name: CD Pipeline (Heroku)

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install, Lint, Test
        run: |
          npm install
      - name: Build
        env:
          NODE_ENV: production
        run: |
          npm run prebuild
          npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.7.8
        with:
          branch: "pipeline"
          dontuseforce: true
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          region: eu
          appdir: "dist"
          # Path relative to appdir
          env_file: "../.env.production"
          # Only variables prefixed with 'HD_' will be recognized by the action. The prefix will automatically be cropped from the name by the action.
        env:
          NODE_ENV: production
          HD_DB_HOST: ${{secrets.HEROKU_DB_HOST}}
          HD_DB_USERNAME: ${{secrets.HEROKU_DB_USERNAME}}
          HD_DB_PASSWORD: ${{secrets.HEROKU_DB_PW}}
          HD_DB_NAME: ${{secrets.HEROKU_DB_NAME}}
          HD_DB_SCHEMA: ${{secrets.HEROKU_DB_SCHEMA}}
          HD_DB_PORT: ${{secrets.HEROKU_DB_PORT}}

