name: Manual CD Pipeline (Heroku)

on:
  pull_request:
    branches:
      - pipeline
  push:
    branches:
      - pipeline

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node-version }}

      - name: Install, Lint, Test
        run: |
          npm install
      - name: Build
        env:
          NODE_ENV: production
        run: |
          npm run prebuild
          npm run build
      - run: git config user.email "britt.foese@gmail.com"
      - run: git config user.name "bfoese"
      - run: git add -A && git commit -m "Updated code"
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.7.8
        with:
          branch: "pipeline"
          dontuseforce: false
          buildpack: heroku/nodejs
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          region: eu
          env_file: "/.env.production"
          # Only variables prefixed with 'HD_' will be recognized by the action. The prefix will automatically be cropped from the name by the action.
        env:
          NODE_ENV: production
          HD_DB_HOST: ${{secrets.HEROKU_DB_HOST}}
          HD_DB_USERNAME: ${{secrets.HEROKU_DB_USERNAME}}
          HD_DB_PASSWORD: ${{secrets.HEROKU_DB_PW}}
          HD_DB_NAME: ${{secrets.HEROKU_DB_NAME}}
          HD_DB_SCHEMA: ${{secrets.HEROKU_DB_SCHEMA}}
          HD_DB_PORT: ${{secrets.HEROKU_DB_PORT}}

