# This is a basic workflow that is manually triggered

name: Deploy Heroku Prod as Container

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
  # workflow_dispatch:
  #   inputs:
  #     branch:
  #       description: 'Branch to deploy'
  #       default: "master"
  #       required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          #branch: ${{ github.event.inputs.branch }}
          branch: main
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontuseforce: false
          usedocker: true
          remote_branch: master # name of herokus remote branch
          docker_heroku_process_type: web
          region: eu
          docker_build_args: |
            GH_PKG_TOKEN
          env_file: ".env.production"
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/edible-garden/health"
          delay: 5
          # Only variables prefixed with 'HD_' will be recognized by the action. The prefix will automatically be cropped from the name by the action.
        env:
          GH_PKG_TOKEN: ${{secrets.GH_PKG_TOKEN}}
          HD_DB_SCHEMA: ${{secrets.HEROKU_DB_SCHEMA}}
          HD_BFEG_CORS_ORIGINS: ${{secrets.CORS_ORIGINS}}
          HD_NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          HD_DB_SSL_CA: ${{secrets.HEROKU_CA}}
          HD_GH_PKG_TOKEN: ${{secrets.GH_PKG_TOKEN}}
          HD_BFEG_AUTH_HASHING_PEPPER: ${{secrets.AUTH_HASHING_PEPPER}}
          HD_BFEG_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_BFEG_JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
          HD_BFEG_JWT_ACCOUNT_ACTION_SECRET: ${{secrets.JWT_ACCOUNT_ACTION_SECRET}}
          HD_BFEG_COOKIE_SIGNATURE_SECRET: ${{secrets.COOKIE_SIGNATURE_SECRET}}
          HD_BFEG_EMAIL_TRANSPORT_URL: ${{secrets.EMAIL_TRANSPORT_URL}}
          HD_BFEG_EMAIL_FROM: ${{secrets.EMAIL_FROM}}
          HD_BFEG_PERSONAL_DATA_ENCRYPTION_KEY: ${{secrets.PERSONAL_DATA_ENCRYPTION_KEY}}
          HD_BFEG_AUTH_FRONTEND_URL: ${{secrets.AUTH_FRONTEND_URL}}
          HD_SERVER_URL: ${{secrets.SERVER_URL}}
          HD_BFEG_CARDIAC_MASSAGE_DYNO_URLS: ${{secrets.CARDIAC_MASSAGE_DYNO_URLS}}
          HD_BFEG_GOOGLE_AUTH_CLIENT_ID: ${{secrets.GOOGLE_AUTH_CLIENT_ID}}
          HD_BFEG_GOOGLE_AUTH_CLIENT_SECRET: ${{secrets.GOOGLE_AUTH_CLIENT_SECRET}}
