# This is a basic workflow that is manually triggered

name: 'lint-test'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 'feat-*'

env:
  BRANCH: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@bfoese'
      - name: Install Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PKG_TOKEN}}
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test

