# This is a basic workflow that is manually triggered

name: Remove old packages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      number:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Number of packages to delete'
        # Default value if no value is explicitly provided
        default: 1
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  remove:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      uses: actions/delete-package-versions@v1.0.3
      with: 
        package-name: 'eg-be-contract'
        num-old-versions-to-delete: ${{ github.event.inputs.number }}
